name: floward_task
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  json_annotation: ^4.6.0
  intl: ^0.17.0
  intl_utils: ^2.7.0
  flutter_svg: ^1.1.1+1
  provider: ^6.0.3
  dio: ^4.0.6
  connectivity: ^3.0.6
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
   - assets/images/

flutter_intl:
  generate: true
  enabled: true
  class_name: S
  main_locale: en
